//! Build-time Rust stub generation from Apache Thrift IDL.

mod ast;
mod generate;

use std::fs;
use std::path::{Path, PathBuf};

use thiserror::Error;

/// Errors reported while parsing, validating, or generating an RPC contract.
#[derive(Debug, Error)]
pub enum CodegenError {
    #[error("failed to read Thrift IDL {path}: {source}")]
    Read {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
    #[error("failed to parse Thrift IDL {path}:{line}:{column}: {message}")]
    Parse {
        path: PathBuf,
        line: usize,
        column: usize,
        message: String,
    },
    #[error("invalid Thrift contract {path}: {message}")]
    InvalidContract { path: PathBuf, message: String },
    #[error("generated invalid Rust for {path}: {source}")]
    InvalidRust {
        path: PathBuf,
        #[source]
        source: syn::Error,
    },
    #[error("failed to write generated Rust {path}: {source}")]
    Write {
        path: PathBuf,
        #[source]
        source: std::io::Error,
    },
}

/// Configures generation of Rust client and server stubs.
#[derive(Clone)]
pub struct Builder {
    runtime_crate: syn::Path,
}

impl Default for Builder {
    fn default() -> Self {
        Self::new()
    }
}

impl Builder {
    pub fn new() -> Self {
        Self {
            runtime_crate: syn::parse_quote!(::coro_rpc),
        }
    }

    /// Overrides the path used by generated code to refer to the runtime crate.
    pub fn runtime_crate(mut self, path: &str) -> Result<Self, syn::Error> {
        self.runtime_crate = syn::parse_str(path)?;
        Ok(self)
    }

    /// Parses `input`, validates the coro_rpc-compatible subset, and writes a
    /// formatted Rust module to `output`.
    pub fn compile(
        &self,
        input: impl AsRef<Path>,
        output: impl AsRef<Path>,
    ) -> Result<(), CodegenError> {
        let input = input.as_ref();
        let output = output.as_ref();
        println!("cargo:rerun-if-changed={}", input.display());

        let source = fs::read_to_string(input).map_err(|source| CodegenError::Read {
            path: input.to_owned(),
            source,
        })?;
        let document = ast::parse(&source, input)?;
        let tokens = generate::generate(&document, &self.runtime_crate, input)?;
        let syntax =
            syn::parse2::<syn::File>(tokens).map_err(|source| CodegenError::InvalidRust {
                path: input.to_owned(),
                source,
            })?;
        let generated = format!(
            "// @generated by coro-rpc-codegen from {}.\n{}",
            input.display(),
            prettyplease::unparse(&syntax)
        );

        if let Some(parent) = output.parent() {
            fs::create_dir_all(parent).map_err(|source| CodegenError::Write {
                path: parent.to_owned(),
                source,
            })?;
        }
        if fs::read_to_string(output).ok().as_deref() != Some(generated.as_str()) {
            fs::write(output, generated).map_err(|source| CodegenError::Write {
                path: output.to_owned(),
                source,
            })?;
        }
        Ok(())
    }
}
