[package]
name = "cakemaster-proto"
version = "0.1.0"
edition = "2024"
description = "Generated RPC contracts used by Cakemaster"
license = "Apache-2.0"
build = "build.rs"

[dependencies]
coro-rpc = { path = "../coro-rpc" }

[build-dependencies]
coro-rpc-codegen = { path = "../coro-rpc-codegen" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
